### ISSUE TITLE
Consider switching to `MaybeUninit<[T; N]>` rather than `[MaybeUninit<T>; N]` before you get too far along with this.

### ISSUE THREAD

**Issue by slightlyoutofphase** [timvermeulen/const-buffer#1]
Just based on my experience writing `staticvec`, `[MaybeUninit<T>; N]` has no real tangible advantages over `MaybeUninit<[T; N]>` for a crate that is already (necessarily) making heavy use of unsafe code internally and is specifically based around const generics.

I started out using `[MaybeUninit<T>; N]` as the internal array for `StaticVec`, but switched to `MaybeUninit<[T; N]>` after about a month or so as it's just significantly more ergonomic to work with in every way.

For example, if using `MaybeUninit<[T; N]>`, your current `from_maybe_uninit_array` could be rewritten to simply take a normal array with the only code being `MaybeUninit::new(array)`.

**Comment by timvermeulen** [comment]
Hey, thanks for the suggestion!

Yeah, using `MaybeUninit<[T; N]>` would definitely simplify `from_maybe_uninit_array`, although I'm hopeful that `transmute` will be capable of doing this in the future. I think it might at the same time make `get` and `get_mut` more complicated, though — they're currently implemented by calling `SliceIndex::get_unchecked[_mut]` on the underlying `[MaybeUninit<T>; N]`. If I use `MaybeUninit<[T; N]>`, I think I'd first have to convert it to a `[MaybeUninit<T>; N]` before indexing it. Wouldn't that just move the problem?

Honestly, the whole reason this crate exists is to get rid of the boilerplate that comes with either of `[MaybeUninit<T>; N]` and `MaybeUninit<[T; N]>`. It started when I tried to see if rewriting `staticvec` to use `[MaybeUninit<T>; N]` would simplify things, and that attempt made clear that neither is very elegant.

One of the main reasons for choosing this representation is to be able to use exisitng slice APIs. For instance, `std::mem::MaybeUninit` now has some APIs that work with arrays/slices, like `uninit_array` and `slice_get_[ref, mut]`. And if `MaybeUninit` ever becomes unconditionally `Copy`, `ConstBuffer::copy_within` will be able to just call `copy_within` on the inner array.

"Before I get too far along with this" isn't really something I worry about, because I don't think the API surface of this crate will grow significantly from this point. And further abstractions like vectors and ring buffers would just use `ConstBuffer` without relying on the exact representation.

**Comment by Akira13641** [comment]
Reasonable enough! Just thought I'd give my two cents, haha.

**Comment by slightlyoutofphase** [comment]
Reasonable enough! Just thought I'd give my two cents, haha.
